package asset.model;

// Generated 2016-2-28 13:52:10 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * AssetAttr generated by hbm2java
 */
@Entity
@Table(name = "asset_attr", catalog = "asset")
public class AssetAttr implements java.io.Serializable {

	private Integer attrId;
	private String attrName;
	private String attrCate;
	private Byte attrStatus;

	public AssetAttr() {
	}

	public AssetAttr(String attrName, String attrCate, Byte attrStatus) {
		this.attrName = attrName;
		this.attrCate = attrCate;
		this.attrStatus = attrStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "attr_id", unique = true, nullable = false)
	public Integer getAttrId() {
		return this.attrId;
	}

	public void setAttrId(Integer attrId) {
		this.attrId = attrId;
	}

	@Column(name = "attr_name")
	public String getAttrName() {
		return this.attrName;
	}

	public void setAttrName(String attrName) {
		this.attrName = attrName;
	}

	@Column(name = "attr_cate")
	public String getAttrCate() {
		return this.attrCate;
	}

	public void setAttrCate(String attrCate) {
		this.attrCate = attrCate;
	}

	@Column(name = "attr_status")
	public Byte getAttrStatus() {
		return this.attrStatus;
	}

	public void setAttrStatus(Byte attrStatus) {
		this.attrStatus = attrStatus;
	}

}
