package asset.model;

// Generated 2016-2-28 13:52:10 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * AssetBaseInfo generated by hbm2java
 */
@Entity
@Table(name = "asset_base_info", catalog = "asset")
public class AssetBaseInfo implements java.io.Serializable {

	private Integer assetId;
	private String assetCate;
	private String assetItNumber;
	private String assetNumber;
	private String assetType;
	private String assetName;
	private String assetMaker;
	private String assetModel;
	private String assetSerial;
	private String assetBornDate;
	private String assetRepairDate;
	private String assetVisitDate;
	private String assetArriveDate;
	private String assetCheckDate;
	private String assetInvoice;
	private String assetProperty;
	private String assetBusiness;
	private String assetRemark;
	private String assetStockStatus;
	private String assetDeviceStatus;
	private String assetDeviceLocation;
	private String assetUseDepartment;
	private String assetUser;
	private String assetUseDate;
	private String assetManDepartment;
	private String assetKeepDepartment;
	private String assetUse;
	private String assetAddMethod;
	private String assetChangeMethod;
	private String assetReduceMethod;
	private String assetRemark2;
	private String assetBeginDate;
	private String assetReserve1;
	private String assetReserve2;
	private String assetReserve3;
	private Date assetAddTime;
	private String assetAddUser;
	private Date assetModifyTime;
	private String assetModifyUser;
	private String assetStatus;

	public AssetBaseInfo() {
	}

	public AssetBaseInfo(String assetCate, String assetItNumber,
			String assetNumber, String assetType, String assetName,
			String assetModel, String assetArriveDate, String assetBusiness) {
		this.assetCate = assetCate;
		this.assetItNumber = assetItNumber;
		this.assetNumber = assetNumber;
		this.assetType = assetType;
		this.assetName = assetName;
		this.assetModel = assetModel;
		this.assetArriveDate = assetArriveDate;
		this.assetBusiness = assetBusiness;
	}

	public AssetBaseInfo(String assetCate, String assetItNumber,
			String assetNumber, String assetType, String assetName,
			String assetMaker, String assetModel, String assetSerial,
			String assetBornDate, String assetRepairDate,
			String assetVisitDate, String assetArriveDate,
			String assetCheckDate, String assetInvoice, String assetProperty,
			String assetBusiness, String assetRemark, String assetStockStatus,
			String assetDeviceStatus, String assetDeviceLocation,
			String assetUseDepartment, String assetUser, String assetUseDate,
			String assetManDepartment, String assetKeepDepartment,
			String assetUse, String assetAddMethod, String assetChangeMethod,
			String assetReduceMethod, String assetRemark2,
			String assetBeginDate, String assetReserve1, String assetReserve2,
			String assetReserve3, Date assetAddTime, String assetAddUser,
			Date assetModifyTime, String assetModifyUser, String assetStatus) {
		this.assetCate = assetCate;
		this.assetItNumber = assetItNumber;
		this.assetNumber = assetNumber;
		this.assetType = assetType;
		this.assetName = assetName;
		this.assetMaker = assetMaker;
		this.assetModel = assetModel;
		this.assetSerial = assetSerial;
		this.assetBornDate = assetBornDate;
		this.assetRepairDate = assetRepairDate;
		this.assetVisitDate = assetVisitDate;
		this.assetArriveDate = assetArriveDate;
		this.assetCheckDate = assetCheckDate;
		this.assetInvoice = assetInvoice;
		this.assetProperty = assetProperty;
		this.assetBusiness = assetBusiness;
		this.assetRemark = assetRemark;
		this.assetStockStatus = assetStockStatus;
		this.assetDeviceStatus = assetDeviceStatus;
		this.assetDeviceLocation = assetDeviceLocation;
		this.assetUseDepartment = assetUseDepartment;
		this.assetUser = assetUser;
		this.assetUseDate = assetUseDate;
		this.assetManDepartment = assetManDepartment;
		this.assetKeepDepartment = assetKeepDepartment;
		this.assetUse = assetUse;
		this.assetAddMethod = assetAddMethod;
		this.assetChangeMethod = assetChangeMethod;
		this.assetReduceMethod = assetReduceMethod;
		this.assetRemark2 = assetRemark2;
		this.assetBeginDate = assetBeginDate;
		this.assetReserve1 = assetReserve1;
		this.assetReserve2 = assetReserve2;
		this.assetReserve3 = assetReserve3;
		this.assetAddTime = assetAddTime;
		this.assetAddUser = assetAddUser;
		this.assetModifyTime = assetModifyTime;
		this.assetModifyUser = assetModifyUser;
		this.assetStatus = assetStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "asset_id", unique = true, nullable = false)
	public Integer getAssetId() {
		return this.assetId;
	}

	public void setAssetId(Integer assetId) {
		this.assetId = assetId;
	}

	@Column(name = "asset_cate", nullable = false)
	public String getAssetCate() {
		return this.assetCate;
	}

	public void setAssetCate(String assetCate) {
		this.assetCate = assetCate;
	}

	@Column(name = "asset_it_number", nullable = false)
	public String getAssetItNumber() {
		return this.assetItNumber;
	}

	public void setAssetItNumber(String assetItNumber) {
		this.assetItNumber = assetItNumber;
	}

	@Column(name = "asset_number", nullable = false)
	public String getAssetNumber() {
		return this.assetNumber;
	}

	public void setAssetNumber(String assetNumber) {
		this.assetNumber = assetNumber;
	}

	@Column(name = "asset_type", nullable = false)
	public String getAssetType() {
		return this.assetType;
	}

	public void setAssetType(String assetType) {
		this.assetType = assetType;
	}

	@Column(name = "asset_name", nullable = false)
	public String getAssetName() {
		return this.assetName;
	}

	public void setAssetName(String assetName) {
		this.assetName = assetName;
	}

	@Column(name = "asset_maker")
	public String getAssetMaker() {
		return this.assetMaker;
	}

	public void setAssetMaker(String assetMaker) {
		this.assetMaker = assetMaker;
	}

	@Column(name = "asset_model", nullable = false)
	public String getAssetModel() {
		return this.assetModel;
	}

	public void setAssetModel(String assetModel) {
		this.assetModel = assetModel;
	}

	@Column(name = "asset_serial")
	public String getAssetSerial() {
		return this.assetSerial;
	}

	public void setAssetSerial(String assetSerial) {
		this.assetSerial = assetSerial;
	}

	@Column(name = "asset_born_date")
	public String getAssetBornDate() {
		return this.assetBornDate;
	}

	public void setAssetBornDate(String assetBornDate) {
		this.assetBornDate = assetBornDate;
	}

	@Column(name = "asset_repair_date")
	public String getAssetRepairDate() {
		return this.assetRepairDate;
	}

	public void setAssetRepairDate(String assetRepairDate) {
		this.assetRepairDate = assetRepairDate;
	}

	@Column(name = "asset_visit_date")
	public String getAssetVisitDate() {
		return this.assetVisitDate;
	}

	public void setAssetVisitDate(String assetVisitDate) {
		this.assetVisitDate = assetVisitDate;
	}

	@Column(name = "asset_arrive_date", nullable = false)
	public String getAssetArriveDate() {
		return this.assetArriveDate;
	}

	public void setAssetArriveDate(String assetArriveDate) {
		this.assetArriveDate = assetArriveDate;
	}

	@Column(name = "asset_check_date")
	public String getAssetCheckDate() {
		return this.assetCheckDate;
	}

	public void setAssetCheckDate(String assetCheckDate) {
		this.assetCheckDate = assetCheckDate;
	}

	@Column(name = "asset_invoice")
	public String getAssetInvoice() {
		return this.assetInvoice;
	}

	public void setAssetInvoice(String assetInvoice) {
		this.assetInvoice = assetInvoice;
	}

	@Column(name = "asset_property")
	public String getAssetProperty() {
		return this.assetProperty;
	}

	public void setAssetProperty(String assetProperty) {
		this.assetProperty = assetProperty;
	}

	@Column(name = "asset_business", nullable = false)
	public String getAssetBusiness() {
		return this.assetBusiness;
	}

	public void setAssetBusiness(String assetBusiness) {
		this.assetBusiness = assetBusiness;
	}

	@Column(name = "asset_remark")
	public String getAssetRemark() {
		return this.assetRemark;
	}

	public void setAssetRemark(String assetRemark) {
		this.assetRemark = assetRemark;
	}

	@Column(name = "asset_stock_status")
	public String getAssetStockStatus() {
		return this.assetStockStatus;
	}

	public void setAssetStockStatus(String assetStockStatus) {
		this.assetStockStatus = assetStockStatus;
	}

	@Column(name = "asset_device_status")
	public String getAssetDeviceStatus() {
		return this.assetDeviceStatus;
	}

	public void setAssetDeviceStatus(String assetDeviceStatus) {
		this.assetDeviceStatus = assetDeviceStatus;
	}

	@Column(name = "asset_device_location")
	public String getAssetDeviceLocation() {
		return this.assetDeviceLocation;
	}

	public void setAssetDeviceLocation(String assetDeviceLocation) {
		this.assetDeviceLocation = assetDeviceLocation;
	}

	@Column(name = "asset_use_department")
	public String getAssetUseDepartment() {
		return this.assetUseDepartment;
	}

	public void setAssetUseDepartment(String assetUseDepartment) {
		this.assetUseDepartment = assetUseDepartment;
	}

	@Column(name = "asset_user")
	public String getAssetUser() {
		return this.assetUser;
	}

	public void setAssetUser(String assetUser) {
		this.assetUser = assetUser;
	}

	@Column(name = "asset_use_date")
	public String getAssetUseDate() {
		return this.assetUseDate;
	}

	public void setAssetUseDate(String assetUseDate) {
		this.assetUseDate = assetUseDate;
	}

	@Column(name = "asset_man_department")
	public String getAssetManDepartment() {
		return this.assetManDepartment;
	}

	public void setAssetManDepartment(String assetManDepartment) {
		this.assetManDepartment = assetManDepartment;
	}

	@Column(name = "asset_keep_department")
	public String getAssetKeepDepartment() {
		return this.assetKeepDepartment;
	}

	public void setAssetKeepDepartment(String assetKeepDepartment) {
		this.assetKeepDepartment = assetKeepDepartment;
	}

	@Column(name = "asset_use")
	public String getAssetUse() {
		return this.assetUse;
	}

	public void setAssetUse(String assetUse) {
		this.assetUse = assetUse;
	}

	@Column(name = "asset_add_method")
	public String getAssetAddMethod() {
		return this.assetAddMethod;
	}

	public void setAssetAddMethod(String assetAddMethod) {
		this.assetAddMethod = assetAddMethod;
	}

	@Column(name = "asset_change_method")
	public String getAssetChangeMethod() {
		return this.assetChangeMethod;
	}

	public void setAssetChangeMethod(String assetChangeMethod) {
		this.assetChangeMethod = assetChangeMethod;
	}

	@Column(name = "asset_reduce_method")
	public String getAssetReduceMethod() {
		return this.assetReduceMethod;
	}

	public void setAssetReduceMethod(String assetReduceMethod) {
		this.assetReduceMethod = assetReduceMethod;
	}

	@Column(name = "asset_remark2")
	public String getAssetRemark2() {
		return this.assetRemark2;
	}

	public void setAssetRemark2(String assetRemark2) {
		this.assetRemark2 = assetRemark2;
	}

	@Column(name = "asset_begin_date")
	public String getAssetBeginDate() {
		return this.assetBeginDate;
	}

	public void setAssetBeginDate(String assetBeginDate) {
		this.assetBeginDate = assetBeginDate;
	}

	@Column(name = "asset_reserve1")
	public String getAssetReserve1() {
		return this.assetReserve1;
	}

	public void setAssetReserve1(String assetReserve1) {
		this.assetReserve1 = assetReserve1;
	}

	@Column(name = "asset_reserve2")
	public String getAssetReserve2() {
		return this.assetReserve2;
	}

	public void setAssetReserve2(String assetReserve2) {
		this.assetReserve2 = assetReserve2;
	}

	@Column(name = "asset_reserve3")
	public String getAssetReserve3() {
		return this.assetReserve3;
	}

	public void setAssetReserve3(String assetReserve3) {
		this.assetReserve3 = assetReserve3;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "asset_add_time", length = 19)
	public Date getAssetAddTime() {
		return this.assetAddTime;
	}

	public void setAssetAddTime(Date assetAddTime) {
		this.assetAddTime = assetAddTime;
	}

	@Column(name = "asset_add_user", length = 11)
	public String getAssetAddUser() {
		return this.assetAddUser;
	}

	public void setAssetAddUser(String assetAddUser) {
		this.assetAddUser = assetAddUser;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "asset_modify_time", length = 19)
	public Date getAssetModifyTime() {
		return this.assetModifyTime;
	}

	public void setAssetModifyTime(Date assetModifyTime) {
		this.assetModifyTime = assetModifyTime;
	}

	@Column(name = "asset_modify_user", length = 11)
	public String getAssetModifyUser() {
		return this.assetModifyUser;
	}

	public void setAssetModifyUser(String assetModifyUser) {
		this.assetModifyUser = assetModifyUser;
	}

	@Column(name = "asset_status")
	public String getAssetStatus() {
		return this.assetStatus;
	}

	public void setAssetStatus(String assetStatus) {
		this.assetStatus = assetStatus;
	}
}
