package asset.model;

// Generated 2016-3-2 22:49:03 by Hibernate Tools 3.4.0.CR1

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * TuserNotice generated by hbm2java
 */
@Entity
@Table(name = "tuser_notice", catalog = "asset")
public class TuserNotice implements java.io.Serializable {

	private Integer noticeId;
	private String noticeUser;
	private String noticeSource;
	private String noticeDesc;
	private String noticeLevel;
	private Date noticeTime;
	private String noticeStatus;

	public TuserNotice() {
	}

	public TuserNotice(String noticeUser) {
		this.noticeUser = noticeUser;
	}

	public TuserNotice(String noticeUser, String noticeSource,
			String noticeDesc, String noticeLevel, Date noticeTime,
			String noticeStatus) {
		this.noticeUser = noticeUser;
		this.noticeSource = noticeSource;
		this.noticeDesc = noticeDesc;
		this.noticeLevel = noticeLevel;
		this.noticeTime = noticeTime;
		this.noticeStatus = noticeStatus;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "notice_id", unique = true, nullable = false)
	public Integer getNoticeId() {
		return this.noticeId;
	}

	public void setNoticeId(Integer noticeId) {
		this.noticeId = noticeId;
	}

	@Column(name = "notice_user", nullable = false)
	public String getNoticeUser() {
		return this.noticeUser;
	}

	public void setNoticeUser(String noticeUser) {
		this.noticeUser = noticeUser;
	}

	@Column(name = "notice_source")
	public String getNoticeSource() {
		return this.noticeSource;
	}

	public void setNoticeSource(String noticeSource) {
		this.noticeSource = noticeSource;
	}

	@Column(name = "notice_desc")
	public String getNoticeDesc() {
		return this.noticeDesc;
	}

	public void setNoticeDesc(String noticeDesc) {
		this.noticeDesc = noticeDesc;
	}

	@Column(name = "notice_level")
	public String getNoticeLevel() {
		return this.noticeLevel;
	}

	public void setNoticeLevel(String noticeLevel) {
		this.noticeLevel = noticeLevel;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "notice_time", length = 19)
	public Date getNoticeTime() {
		return this.noticeTime;
	}

	public void setNoticeTime(Date noticeTime) {
		this.noticeTime = noticeTime;
	}

	@Column(name = "notice_status")
	public String getNoticeStatus() {
		return this.noticeStatus;
	}

	public void setNoticeStatus(String noticeStatus) {
		this.noticeStatus = noticeStatus;
	}

}
